config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'home/index'
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :charges
  get 'success', to: 'charges#success'
  get 'fail', to: 'charges#fail'
  get 'payment_data', to: 'charges#payment_data'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/payment_datum.rb
class PaymentDatum < ApplicationRecord

  paginates_per 20

  def status_view
    if status
      :success
    else
      :fail
    end
  end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
require "stripe"

class ChargesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @price = params[:price]
  end

  def create
    Stripe.api_key = 'sk_test_51MazEpAtaSHqtwmKOZiRQSoi8iBLOMjSA0GSXdONnIBz4HpvGNtepJZYfLSTfrOex8WdYTjgbOzDaH4gYFlTdiw800sfWciFUx'    
    begin
      intent = Stripe::PaymentIntent.create(
        payment_method: params[:payment_method_id],
        amount: params[:amount],
        currency: 'usd',
        return_url: "#{ENV['HOST']}/success",
        confirmation_method: 'manual',
        confirm: true,
      )
    rescue Stripe::CardError => e
      return [200, { error: e.message }.to_json]
    end
    generate_response(intent)
  end

  def generate_response(intent)
    if intent.next_action.type == "redirect_to_url" && intent.status == 'requires_action'
      render json: {
        url: intent.next_action['redirect_to_url']['url']
      }.to_json
    else
      PaymentDatum.create(payment_token: intent.id, amount:intent.amount/100.0)
      render json: { url: "#{ENV['HOST']}/fail" }.to_json 
    end
  end

  def success
    begin
    intent = Stripe::PaymentIntent.retrieve(params['payment_intent'])
    if intent.status == 'requires_confirmation'
      intent = Stripe::PaymentIntent.confirm(
        params['payment_intent']
      )
    end
    rescue Stripe::CardError => e
      puts "A payment error occurred: #{e.error.message}"
    rescue Stripe::InvalidRequestError => e
      puts "An invalid request occurred."
    rescue Stripe::StripeError => e
      puts "Another problem occurred, maybe unrelated to Stripe."
    else
      puts "No error."
    end
    if intent.status == "succeeded"
      PaymentDatum.create(payment_token: intent.id, amount:intent.amount/100.0 , status: true)
    else
      PaymentDatum.create(payment_token: intent.id, amount:intent.amount/100.0)
      redirect_to "#{ENV['HOST']}/fail"
    end
  end

  def fail
  end

  def payment_data
    @payment_data = PaymentDatum.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/charges/_index.html.erb
<style>
.card-dd{
  width:500px; /* or whatever width you want. */
  max-width:500px; /* or whatever width you want. */
}
</style>
<div class="row align-items-start mt-4">
  <div class="col">
  </div>
  <div class="col">
    <form id='payment-form' action="/charges" method= "post">
      <label>
        Card details
        <!-- placeholder for Elements -->
        <div class="card-dd"><br>
          <div id="card-element">
          </div>
        </div>
      </label>
      <hr>
      <button type="submit" class="btn btn-primary">Submit Payment</button>
    </form>
  </div>
  <div class="col">
  </div>
</div>

<script>
const stripe = Stripe('pk_test_51MazEpAtaSHqtwmKtBjmcG80WnGqACuEhh8lAggSCcdPQ3oIVZ2LF34Zhfm6hIgWkOKzna9EIWgMJQtTjTL1tmsV00QA5rlUX5');

var elements = stripe.elements();

// Set up Stripe.js and Elements to use in checkout form
var style = {
    base: {
      color: "#32325d",
      fontFamily: 'Arial, sans-serif',
      fontSmoothing: "antialiased",
      fontSize: "16px",
      "::placeholder": {
        color: "#32325d"
      }
    },
    invalid: {
      fontFamily: 'Arial, sans-serif',
      color: "#fa755a",
      iconColor: "#fa755a"
    }
  };

const cardElement = elements.create("card", { style: style });
cardElement.mount('#card-element'); 

const form = document.getElementById('payment-form');

form.addEventListener('submit', async (event) => {
  // We don't want to let default form submission happen here,
  // which would refresh the page.
  event.preventDefault();

  const result = await stripe.createPaymentMethod({
    type: 'card',
    card: cardElement,
    billing_details: {
      // Include any additional collected billing details.
      name: 'Jenny Rosen',
    },
  })

  stripePaymentMethodHandler(result);
});


const stripePaymentMethodHandler = async (result) => {
  if (result.error) {
    // Show error in payment form
  } else {
    // Otherwise send paymentMethod.id to your server (see Step 4)
    const res = await fetch('/charges.json', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        payment_method_id: result.paymentMethod.id,
        amount: "<%= @price %>",
      }),
    })
    const paymentResponse = await res.json();
    handleServerResponse(paymentResponse);
    window.location = paymentResponse.url;
    // Handle server response (see Step 4)
  }
}

const handleServerResponse = async (response) => {
  if (response.error) {
    // Show error from server on payment form
  } else if (response.requires_action) {
    // Use Stripe.js to handle the required card action
    const { error: errorAction, paymentIntent } =
      await stripe.handleCardAction(response.payment_intent_client_secret);

    if (errorAction) {
      // Show error from Stripe.js in payment form
    } else {
      // The card action has been handled
      // The PaymentIntent can be confirmed again on the server
      const serverResponse = await fetch('/confirm_payment_intent', {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ payment_intent_id: paymentIntent.id })
      });
      handleServerResponse(await serverResponse.json());
    }
  } else {
    // Show success message
  }
  stripe.confirmCardPayment(
    response.client_secret,
    {
      payment_method: {card: cardElement},
      return_url: "#{ENV['HOST']}/confirm_payment_intent"
    },
    // Disable the default next action handling.
    {handleActions: false}
  ).then(function(result) {
    // Handle result.error or result.paymentIntent
    // More details in Step 2.
  });
}
</script>

app/views/charges/fail.html.erb
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" />
<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
<style type="text/css">

    body
    {
        background:#f2f2f2;
    }

    .payment
  {
    border:1px solid #f01b1b;
    height:280px;
        border-radius:20px;
        background:#fff;
  }
    .payment_header
    {
      background:#f01b1b;
      padding:20px;
        border-radius:20px 20px 0px 0px;
  
    }

    .check
    {
      margin:0px auto;
      width:50px;
      height:50px;
      border-radius:100%;
      background:#fff;
      text-align:center;
    }

    .check i
    {
      vertical-align:middle;
      line-height:50px;
      font-size:30px;
    }

    .content 
    {
        text-align:center;
    }

    .content  h1
    {
        font-size:25px;
        padding-top:25px;
    }

    .content a
    {
        width:200px;
        height:35px;
        color:#fff;
        border-radius:30px;
        padding:5px 10px;
        background:#f01b1b;
        transition:all ease-in-out 0.3s;
    }

    .content a:hover
    {
        text-decoration:none;
        background:#000;
    }

</style>

<div class="container">
   <div class="row">
      <div class="col-md-6 mx-auto mt-5">
         <div class="payment">
            <div class="payment_header">
               <div class="check"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i></div>
            </div>
            <div class="content">
               <h1>Your payment failed</h1>
               <p>For check the payment status <a href="<%= payment_data_url %>"> Click Here </a></p>
               <a href="<%= root_path %>">Try Agian</a>
            </div>
            
         </div>
      </div>
   </div>
</div>

app/views/charges/index.html.erb
<style>
.card-dd{
   width:500px; /* or whatever width you want. */
   max-width:500px; /* or whatever width you want. */
}
</style>
<div class="row align-items-start mt-4">
    <div class="col">
      
    </div>
    <div class="col">
 
<form id='payment-form' action="/charges" method= "post">
  <label>
    Card details
    <!-- placeholder for Elements -->
    <div class="card-dd"><br>
      <div id="card-element">
      </div>
    </div>
  </label>
  <hr>
  <button type="submit" class="btn btn-primary">Submit Payment</button>
</form>
  </div>
    <div class="col">
      
    </div>
  </div>

<script>
const stripe = Stripe('pk_test_51MazEpAtaSHqtwmKtBjmcG80WnGqACuEhh8lAggSCcdPQ3oIVZ2LF34Zhfm6hIgWkOKzna9EIWgMJQtTjTL1tmsV00QA5rlUX5');

var elements = stripe.elements();

// Set up Stripe.js and Elements to use in checkout form

const cardElement = elements.create('card');
cardElement.mount('#card-element');

const form = document.getElementById('payment-form');

form.addEventListener('submit', async (event) => {
  // We don't want to let default form submission happen here,
  // which would refresh the page.
  event.preventDefault();

  const result = await stripe.createPaymentMethod({
    type: 'card',
    card: cardElement,
    billing_details: {
      // Include any additional collected billing details.
      name: 'Jenny Rosen',
    },

  })

  stripePaymentMethodHandler(result);
});


const stripePaymentMethodHandler = async (result) => {
  if (result.error) {
    // Show error in payment form
  } else {
    // Otherwise send paymentMethod.id to your server (see Step 4)
    const res = await fetch('/charges.json', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        payment_method_id: result.paymentMethod.id,
        amount: "<%= @price %>",
      }),
    })
    const paymentResponse = await res.json();
    handleServerResponse(paymentResponse);
    window.location = paymentResponse.url;
    // Handle server response (see Step 4)
  }
}

const handleServerResponse = async (response) => {
  if (response.error) {
    // Show error from server on payment form
  } else if (response.requires_action) {
    // Use Stripe.js to handle the required card action
    const { error: errorAction, paymentIntent } =
      await stripe.handleCardAction(response.payment_intent_client_secret);

    if (errorAction) {
      // Show error from Stripe.js in payment form
    } else {
      // The card action has been handled
      // The PaymentIntent can be confirmed again on the server
      const serverResponse = await fetch('/confirm_payment_intent', {
        method: 'GET',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ payment_intent_id: paymentIntent.id })
      });
      handleServerResponse(await serverResponse.json());
    }
  } else {
    // Show success message
  }
  stripe.confirmCardPayment(
    response.client_secret,
    {
      payment_method: {card: cardElement},
      return_url: "#{ENV['HOST']}/confirm_payment_intent"
    },
    // Disable the default next action handling.
    {handleActions: false}
  ).then(function(result) {
    // Handle result.error or result.paymentIntent
    // More details in Step 2.
  });
}
</script>

app/views/charges/index.js.erb
html = $('<%= j render partial: 'charges/index' %>');
$('.modal-body').replaceWith(html);

app/views/charges/payment_data.html.erb
<% if @payment_data.present? %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Token</th>
      <th scope="col">Amount</th>
      <th scope="col">Status</th>
      <th scope="col">created At</th>
      
    </tr>
  </thead>
  <tbody>
    <% @payment_data.each do |data| %>
      <tr>
        <td> <%= data.id %> </td> 
        <td> <%= data.payment_token %> </td>
        <td> $<%= data.amount %> </td>
        <td> <%= data.status_view %> </td>
        <td> <%= data.created_at %> </td>
      </tr>
    <% end %>
  </tbody>
</table> 

<div class="d-flex justify-content-center">
  <%= paginate @payment_data %>
</div>
<% else %>
<div class="d-flex justify-content-center">
  There is No PaymentIntent.
</div>
<% end %>

app/views/charges/success.html.erb
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
<style>
  body {
    text-align: center;
    background: #EBF0F5;
  }
    h1 {
      color: #88B04B;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-weight: 900;
      font-size: 40px;
      margin-bottom: 10px;
    }
    p {
      color: #404F5E;
      font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
      font-size:20px;
      margin: 0;
    }
  i {
    color: #9ABC66;
    font-size: 100px;
    line-height: 200px;
    margin-left:-15px;
  }
  .card {
    background: white;
    padding: 60px;
    border-radius: 4px;
    box-shadow: 0 2px 3px #C8D0D8;
    display: inline-block;
    margin: 150px auto;
  }
</style>
<div class="card">
  <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
    <i class="checkmark">✓</i>
  </div>
  <h1>Success</h1> 
  <p>Payment Successfully!</p>
</div>

app/views/home/index.html.erb
<h2 class="text-center mt-3">Select The Plan</h2>
<div class= "row m-5">
  <div class= "col-4">
    <div class="card">
      <div class="card-header">
        Silver
      </div>
      <div class="card-body">
        <h5 class="card-title"><b>Price:</b> $10 </h5>
        <p class="card-text">Subscribe for silver plan.</p>
        <div class="cd-pricing-body">
					<ul class="cd-pricing-features">
						<li><em>256MB</em> Memory</li>
						<li><em>1</em> User</li>
						<li><em>1</em> Website</li>
						<li><em>1</em> Domain</li>
						<li><em>Unlimited</em> Bandwidth</li>
						<li><em>24/7</em> Support</li>
					</ul>
				</div>
        <button type="button" class="btn btn-primary" data-price="1000" data-bs-toggle="modal" data-bs-target="#card-modal" onClick="PriceData(this)">
          Pay $10
        </button>
      </div>
    </div>
  </div>

  <div class= "col-4">
    <div class="card">
      <div class="card-header">
        Gold
      </div>
      <div class="card-body">
        <h5 class="card-title"><b>Price:</b> $20 </h5>
        <p class="card-text">Subscribe for gold plan.</p>
        <div class="cd-pricing-body">
					<ul class="cd-pricing-features">
						<li><em>512MB</em> Memory</li>
						<li><em>3</em> Users</li>
						<li><em>5</em> Websites</li>
						<li><em>7</em> Domains</li>
						<li><em>Unlimited</em> Bandwidth</li>
						<li><em>24/7</em> Support</li>
					</ul>
				</div>
        <button type="button" class="btn btn-primary" data-price="2000" data-bs-toggle="modal" data-bs-target="#card-modal" onClick="PriceData(this)">
          Pay $20
        </button>
      </div>
    </div>
  </div>

  <div class= "col-4">
    <div class="card">
      <div class="card-header">
        Platinum
      </div>
      <div class="card-body">
        <h5 class="card-title"><b>Price:</b> $50 </h5>
        <p class="card-text">Subscribe for platinum plan.</p>
        <div class="cd-pricing-body">
					<ul class="cd-pricing-features">
						<li><em>1024MB</em> Memory</li>
						<li><em>5</em> Users</li>
						<li><em>10</em> Websites</li>
						<li><em>10</em> Domains</li>
						<li><em>Unlimited</em> Bandwidth</li>
						<li><em>24/7</em> Support</li>
					</ul>
				</div>
        <button type="button" class="btn btn-primary" data-price="5000" data-bs-toggle="modal" data-bs-target="#card-modal" onClick="PriceData(this)">
          Pay $50
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="card-modal" tabindex="-1" aria-labelledby="cardModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style="width: 600px;">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="cardModalLabel">Payment Intent</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      </div>
      <br>
    </div>
  </div>
</div>

<script>
  function PriceData(e){
    $.ajax({
      url: "/charges",
      type: "GET",
      data: {"price" : $(e).attr('data-price')},
      dataType: "script"
    });
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid justify-content-start">
        <span class="navbar-text">
          <%= link_to 'Stripe Demo', root_path, class: 'nav-link' %>
        </span>
        <span class="navbar-text">
          <%= link_to 'Payment Data', payment_data_path, class: 'nav-link' %>
        <span>
      </div>
    </nav>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>